# Generated by Django 3.1.7 on 2021-04-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=55)),
                ('produto', models.CharField(max_length=50)),
                ('datacp', models.DateField(blank=True, null=True)),
                ('codigocp', models.CharField(blank=True, max_length=18, null=True)),
                ('statuscp', models.CharField(blank=True, max_length=50, null=True)),
                ('datast', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=40, null=True)),
                ('finalizado', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('idpg', models.AutoField(primary_key=True, serialize=False)),
                ('datapg', models.DateField()),
                ('valor', models.FloatField()),
                ('parcelas', models.IntegerField(blank=True, null=True)),
                ('valorparc', models.FloatField(blank=True, null=True)),
                ('statuspg', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pagamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rastreios',
            fields=[
                ('idrst', models.AutoField(primary_key=True, serialize=False)),
                ('idprod', models.IntegerField()),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('produto', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo', models.CharField(blank=True, max_length=15, null=True)),
                ('data', models.CharField(blank=True, max_length=12, null=True)),
                ('hora', models.CharField(blank=True, max_length=5, null=True)),
                ('local', models.CharField(blank=True, max_length=20, null=True)),
                ('mens', models.CharField(blank=True, max_length=150, null=True)),
                ('finalizado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rastreios',
                'managed': False,
            },
        ),
    ]
